### Variables Globales
@baseUrl = http://localhost:9191/api/v1
@authToken = ///CREDENCIALES


### Obtener todos los platos (Paginado)
GET {{baseUrl}}/dishes?page=0&size=10
Authorization: Bearer {{authToken}}

### Obtener plato por ID
GET {{baseUrl}}/dishes/1
Authorization: Bearer {{authToken}}

### Crear un nuevo plato
POST {{baseUrl}}/dishes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Pasta Carbonara",
    "description": "Clásica pasta italiana con huevo, queso y guanciale",
    "price": 12.50,
    "active": true
}

### Actualizar un plato
PUT {{baseUrl}}/dishes/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Pasta Carbonara Premium",
    "description": "Pasta artesanal con trufa negra",
    "price": 18.00,
    "active": true
}

### Eliminar un plato
DELETE {{baseUrl}}/dishes/1
Authorization: Bearer {{authToken}}
