### Variables Globales
@baseUrl = http://localhost:9191/api/v1
@authToken = ///CREDENCIALES

### Obtener todos los restaurantes
GET {{baseUrl}}/restaurants
Authorization: Bearer {{authToken}}

### Obtener restaurante por ID
GET {{baseUrl}}/restaurants/1
Authorization: Bearer {{authToken}}

### Crear un nuevo restaurante
POST {{baseUrl}}/restaurants
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "La Trattoria",
    "address": "Calle Falsa 123, Ciudad Gourmet",
    "menuIds": [1],
    "tableIds": [1, 2, 3]
}

### Actualizar un restaurante
PUT {{baseUrl}}/restaurants/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "La Trattoria di Kaisten",
    "address": "Calle Real 456, Distrito Gastronómico",
    "menuIds": [1, 2],
    "tableIds": [1, 2, 3, 4]
}

### Eliminar un restaurante
DELETE {{baseUrl}}/restaurants/1
Authorization: Bearer {{authToken}}
