### Variables Globales
@baseUrl = http://localhost:9191/api/v1
@authToken = ///CREDENCIALES


### Obtener todas las mesas
GET {{baseUrl}}/tables
Authorization: Bearer {{authToken}}

### Obtener mesa por ID
GET {{baseUrl}}/tables/1
Authorization: Bearer {{authToken}}

### Crear una nueva mesa
POST {{baseUrl}}/tables
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "tableNumber": 5,
    "capacity": 4,
    "isAvailable": true,
    "restaurantId": 1
}

### Actualizar una mesa
PUT {{baseUrl}}/tables/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "tableNumber": 5,
    "capacity": 6,
    "isAvailable": false,
    "restaurantId": 1
}

### Eliminar una mesa
DELETE {{baseUrl}}/tables/1
Authorization: Bearer {{authToken}}
