### Variables Globales
@baseUrl = http://localhost:9191/api/v1
@authToken = ///CREDENCIALES

### 1. Registrar un usuario como RESTAURANT (Dueño) - Via Auth Controller
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "firstName": "Admin2",
    "lastName": "Restaurant",
    "email": "admin2@restaurant.com",
    "password": "password123",
    "role": "RESTAURANT"
}

### 2. Registrar un usuario como CLIENTE - Via Auth Controller
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "firstName": "Maria",
    "lastName": "Lopez",
    "email": "maria@cliente.com",
    "password": "password123",
    "role": "CLIENT"
}

### 3. Listar usuarios (Requiere Auth)
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

