package dev.kaisten.RestaurantAPI.mapper;

import dev.kaisten.RestaurantAPI.dto.DishRequestDTO;
import dev.kaisten.RestaurantAPI.dto.DishResponseDTO;
import dev.kaisten.RestaurantAPI.entity.Dish;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import java.util.List;

@Mapper(componentModel = "spring")
public interface DishMapper {

    DishResponseDTO toDto(Dish dish);

    List<DishResponseDTO> toDtoList(List<Dish> dishes);

    @Mapping(target = "id", ignore = true) // ID is generated by the database
    @Mapping(target = "active", expression = "java(requestDTO.active() != null ? requestDTO.active() : true)")
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "lastModifiedBy", ignore = true)
    Dish toEntity(DishRequestDTO requestDTO);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "active", expression = "java(requestDTO.active() != null ? requestDTO.active() : dish.getActive())")
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "lastModifiedBy", ignore = true)
    void updateEntityFromDto(DishRequestDTO requestDTO, @MappingTarget Dish dish);
}
